import { NewsForm } from "../config/components/organisms/News";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const NewsPage = () => {
  return (
    <>
      <div className="container mx-auto py-10">
        <NewsForm />
      </div>
    </>
  );
};
export default NewsPage;
