import { ProductDetail } from "../../components/component/organisms/ProductDetail";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const HomePage = () => {
  return (
    <>
      <div className="">
        <ProductDetail />
      </div>
    </>
  );
};
export default HomePage;
