import { Cart } from "../config/components/organisms/Cart";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const CartPage = () => {
  return (
    <>
      <div>
        <Cart />
      </div>
    </>
  );
};
export default CartPage;
