import { AllProducts } from "../components/component/organisms/ListProduct";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};

const Products = () => {
  return (
    <>
      <div className="container mx-auto pb-10">
        <AllProducts />
      </div>
    </>
  );
};

export default Products;
