export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const AccountPage = () => {
  return (
    <>
      <div className=""></div>
    </>
  );
};
export default AccountPage;
