import { AllSearchProducts } from "../config/components/organisms/ListProduct";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const SearchPage = () => {
  return (
    <>
      <div className="container mx-auto pb-10">
        <AllSearchProducts />
      </div>
    </>
  );
};
export default SearchPage;
